# Generated by Django 5.1.3 on 2024-11-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_tree_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='season',
            field=models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('autumn', 'Autumn'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
