# Generated by Django 5.1.3 on 2024-11-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_tree_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='care_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
