# Generated by Django 5.1.3 on 2024-11-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_cart'),
        ('trees', '0005_tree_num_ratings_tree_total_rating_rating'),
    ]

    operations = [
    ]
