# Generated by Django 5.1.3 on 2024-11-29 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_guide', '0001_initial'),
        ('trees', '0007_remove_cart_created_at_alter_tree_num_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='name',
        ),
        migrations.AddField(
            model_name='plant',
            name='tree_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trees.tree'),
            preserve_default=False,
        ),
    ]
