# Generated by Django 5.1.3 on 2024-11-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_guide', '0004_rename_temp_field_plant_dummy_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
